### ISSUE TITLE
Adding support for "Confirmable Notification"

### ISSUE THREAD

**Issue by asoloway64** [core-wg/conditional-attributes#2]
OMA LwM2M added support for additional attributes that should be reflected back into the dynlink draft to avoid fragmentation. One of those attributes is called "Confirmable Notification".

The current LwM2M Core Spec currently has this statement:
"The behaviour of Notification class attributes MUST follow [DynLink] unless stated otherwise in this specification. Note:
The attributes epmin, epmax, con and edge are specified in this specification but currently not referenced in [DynLink]."

The goal would be to change that statement to:
"The behavior of all Attributes SHOULD follow [DynLink]."

Below is content to consider for the dynlink draft:
"The Notification Confirmable Attribute indicates whether a Notification resulting from an Observation of a specific Object, Object
Instance, Resource, Resource Instance MUST be sent over confirmable transport. If a Notification includes several Objects or Object Instances or Resources or Resource Instances or a combination thereof, then this Notification MUST be sent over confirmable transport if at least one of the Notification components has con=1."

**Comment by bsilverajan** [comment]
"Con" has now been added to the draft
