### ISSUE TITLE
Iotdir early review comment (Intended Status)

### ISSUE THREAD

**Issue by bsilverajan** [core-wg/conditional-attributes#31]
From https://mailarchive.ietf.org/arch/msg/core/vSrEc-59XQeYf3V-LoMNTJ-uPs8/

Issue:
1- The draft states the Intended status as Informational, Should the Intended
status be: Standards Track?

**Comment by bsilverajan** [comment]
The document is now Standards Track

**Comment by inesrob** [comment]
Ok, thank you
