### ISSUE TITLE
Iotdir early review comment (IANA Considerations)

### ISSUE THREAD

**Issue by bsilverajan** [core-wg/conditional-attributes#32]
From https://mailarchive.ietf.org/arch/msg/core/vSrEc-59XQeYf3V-LoMNTJ-uPs8/

The IANA Considerations should reference the protocol category group (core-parameters?) https://www.iana.org/assignments/core-parameters/core-parameters.xhtml

**Comment by inesrob** [comment]
Also, it would be nice if a caption on Table 3 could be added. Thank you.

**Comment by bsilverajan** [comment]
Table 3 is now captioned as mentioned

**Comment by bsilverajan** [comment]
@inesrob As this was the last remaining issue in the IOTDIR early review, can this issue be closed and the status of the draft be updated now?

**Comment by bsilverajan** [comment]
Thank you!
