### ISSUE TITLE
Iotdir early review comment (idnits)

### ISSUE THREAD

**Issue by bsilverajan** [core-wg/conditional-attributes#33]
From https://mailarchive.ietf.org/arch/msg/core/vSrEc-59XQeYf3V-LoMNTJ-uPs8/

Trying to run idnits from the URL, using https://author-tools.ietf.org/idnits I
get,"{"error":"Opening and ending tag mismatch: li line 1195 and style, line
1203, column 9 (draft-ietf-core-conditional-attributes-06.html, line 1203)"}"

**Comment by inesrob** [comment]
I understand this is solved in version 07, right?
