### ISSUE TITLE
Review of draft-ietf-core-conditional-attributes-07 [Section 3.5.0]

### ISSUE THREAD

**Issue by bsilverajan** [core-wg/conditional-attributes#41]
From https://mailarchive.ietf.org/arch/msg/core/mBfPbB892W95BnAHEq9wtv8aH9Y/

I think it's worth mentioning already here that some attributes are 
subject to "c.pmin" (if specified), which is defined later in Section 3.6.1.

**Comment by bsilverajan** [comment]
I would prefer to keep the discussions of notification and control attributes separate, as interactions will occur in any case with attributes other than pmin (eg pmax).

Perhaps it can be mentioned earlier in the section or later, when there is a discussion about server processing of notification and control attributes?

**Comment by marco-tiloca-sics** [comment]
> Perhaps it can be mentioned earlier in the section or later, when there is a discussion about server processing of notification and control attributes?

Sure, that should work.

**Comment by bsilverajan** [comment]
Section 3.7 now clarifies this as following:

When Conditional Notification Attributes and Conditional Control Attributes are present in the same query, notifications may be subjected to the presence of a Conditional Control Attribute such as "c.pmin" or "c.pmax".
