### ISSUE TITLE
Review of draft-ietf-core-conditional-attributes-07  [Appendix B]

### ISSUE THREAD

**Issue by bsilverajan** [core-wg/conditional-attributes#47]
From https://mailarchive.ietf.org/arch/msg/core/mBfPbB892W95BnAHEq9wtv8aH9Y/

* The figures in the four examples can use AASVG.

**Comment by bsilverajan** [comment]
Both this issue as well as part of issue #38 refer to the usage of aasvg

Using AASVG does not really significantly add much in this draft (as it may in other cases or drafts, eg complex state machine diagrams). In addition, for some figures, some level of redrawing seems needed. 

I would prefer to leave the figures as is, since I feel they already convey the information needed quite effectively.

**Comment by marco-tiloca-sics** [comment]
Sure, it would be mostly stylistic. I think there's no issue in keeping the figures as-is, but expect the same request to come back again as the document moves forward :-)

**Comment by bsilverajan** [comment]
Thanks, I'll close it for now and if the request comes up, I'll re-open this issue
