### ISSUE TITLE
The value of the Band attribute

### ISSUE THREAD

**Issue by asoloway64** [core-wg/conditional-attributes#7]
The band attribute is defined as a boolean type, but the use of the band attribute is determined by its presence, not its value. We should probably explicitly explain that.

**Comment by bsilverajan** [comment]
This is a good catch. Do we need the band attribute to have a value to begin with? This query component can simply be a name, instead of name-value pair (i.e band does not have any datatype). 

Example:
`/temperature?band&gt="30"&lt="35"`

**Comment by bsilverajan** [comment]
Usage of band is now indicated purely by its presence and not its value in -02
