### ISSUE TITLE
The band example uses Abmn, Abmx, Bbmn and Bbmx

### ISSUE THREAD

**Issue by asoloway64** [core-wg/conditional-attributes#8]
When reading the example of the use of band, I was initially confused on the representation of the other control attributes. Should we change those examples to use lt, gt and band?

**Comment by bsilverajan** [comment]
You're referring to this sentence in Implementation Considerations:

`For example: Given BandA (Abmn=10, Bbmx=20) and BandB (Bbmn=21, Bbmx=30)......`

I have no objections if we make the change you propose so it says:

`For example: Given 2 bands, A (band=1, gt=1, lt=20) and B (band=1, gt=21, lt=30)....`

Is this what you meabnt?

**Comment by asoloway64** [comment]
Yep, exactly.

**Comment by bsilverajan** [comment]
As agreed at the Interim Meeting on 29 Sept 21, the text referring to multiple bands can be removed. This is now removed in version 02 of the draft
