### ISSUE TITLE
Format of pdf

### ISSUE THREAD

**Issue by asoloway64** [core-wg/conditional-attributes#9]
When I look at the pdf version from the web site https://datatracker.ietf.org/doc/draft-ietf-core-conditional-attributes/, the Implementation Considerations section text is not displayed as normal text.

**Comment by cabo** [comment]
The page 9 looks good to me, but it is scaled down to make room for the overly long like starting with `#define IN_BAND`.  This needs to be split up so it fits into the 72-character line width.

(The fixed submission interface will stop using the legacy formatters if only the XML is submitted, so the reduction may "solve" itself, but the line is still too long.)

**Comment by asoloway64** [comment]
I created Pull Request #10 to split up that line.

**Comment by bsilverajan** [comment]
Closing this issue as both have been fixed in the current working copy:

- `#define IN_BAND` line split to account for page width
- IANA consideration section properly formatted
